project:
  type: website
  output-dir: docs

website:
  title: "HARMONY Race Sub-analysis"
  navbar:
    left:
      - href: summary.qmd
        text: Summary
      - href: revision.qmd
        text: Revision

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    embed-resources: true
